apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiz-app-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-app-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: wiz-app-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiz-web-app
  template:
    metadata:
      labels:
        app: wiz-web-app
    spec:
      serviceAccountName: wiz-app-sa
      containers:
      - name: wiz-web-app
        image: us-central1-docker.pkg.dev/clgcporg10-185/wiz-repo/wiz-web-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://todo_user:TodoPassword123!@10.0.1.2:27017/todo_db?authSource=todo_db"
---
apiVersion: v1
kind: Service
metadata:
  name: wiz-web-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: wiz-web-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiz-web-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wiz-web-service
            port:
              number: 80